name: Annotation Suggestions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the train_test_bert_with_categorical_features branch
on:
  pull_request:
    paths:
      - '**.py'
    branches: [master, train_test_bert_with_categorical_features]

jobs:
  suggest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so that typilus can access it.
    - uses: actions/checkout@v3
    - uses: Karim-53/typilus-action@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUGGESTION_CONFIDENCE_THRESHOLD: 0.9   # Configure this to limit the confidence of suggestions on un-annotated locations. A float in [0, 1]. Default 0.8
        DISAGREEMENT_CONFIDENCE_THRESHOLD: 0.95  # Configure this to limit the confidence of suggestions on annotated locations.  A float in [0, 1]. Default 0.95
